# Generated by Django 5.2.11 on 2026-03-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pet_images/'),
        ),
        migrations.AddField(
            model_name='pet',
            name='microchip_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='price_level',
            field=models.CharField(blank=True, choices=[('ราคาปกติ', 'ราคาปกติ'), ('ราคาพิเศษ', 'ราคาพิเศษ')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'เพศผู้'), ('F', 'เพศเมีย')], max_length=10, null=True),
        ),
    ]
