# Generated by Django 5.2.11 on 2026-03-17 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_pet_customer_id_pet_image_pet_microchip_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='image',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='microchip_number',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='price_level',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='sex',
        ),
    ]
