# Generated by Django 5.2.11 on 2026-03-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_pet_customer_id_remove_pet_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='customer_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='รหัสลูกค้า'),
        ),
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pet_images/', verbose_name='รูปภาพสัตว์เลี้ยง'),
        ),
        migrations.AddField(
            model_name='pet',
            name='microchip_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='เลขที่ชิป'),
        ),
        migrations.AddField(
            model_name='pet',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='เบอร์มือถือ'),
        ),
        migrations.AddField(
            model_name='pet',
            name='price_level',
            field=models.CharField(blank=True, choices=[('ราคาปกติ', 'ราคาปกติ'), ('ราคาพิเศษ', 'ราคาพิเศษ')], max_length=50, null=True, verbose_name='ระดับราคา'),
        ),
        migrations.AddField(
            model_name='pet',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหตุ'),
        ),
        migrations.AddField(
            model_name='pet',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'ตัวผู้'), ('F', 'ตัวเมีย')], max_length=10, null=True, verbose_name='เพศ'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันเกิด'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='สายพันธุ์'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(max_length=50, verbose_name='ประเภทสัตว์'),
        ),
    ]
