# Generated by Django 5.2.11 on 2026-03-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_pet_customer_id_pet_image_pet_microchip_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vet',
            name='name',
        ),
        migrations.AddField(
            model_name='vet',
            name='address_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ที่อยู่บรรทัดที่ 1'),
        ),
        migrations.AddField(
            model_name='vet',
            name='address_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ที่อยู่บรรทัดที่ 2'),
        ),
        migrations.AddField(
            model_name='vet',
            name='degree',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='วุฒิการศึกษา'),
        ),
        migrations.AddField(
            model_name='vet',
            name='doctor_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='รหัสแพทย์'),
        ),
        migrations.AddField(
            model_name='vet',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='อีเมล'),
        ),
        migrations.AddField(
            model_name='vet',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่อ'),
        ),
        migrations.AddField(
            model_name='vet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vet_images/', verbose_name='รูปถ่ายแพทย์'),
        ),
        migrations.AddField(
            model_name='vet',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='นามสกุล'),
        ),
        migrations.AddField(
            model_name='vet',
            name='license_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='วันหมดอายุใบอนุญาต'),
        ),
        migrations.AddField(
            model_name='vet',
            name='license_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='เลขที่ใบอนุญาตประกอบวิชาชีพ'),
        ),
        migrations.AddField(
            model_name='vet',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='เลขประจำตัวประชาชน'),
        ),
        migrations.AddField(
            model_name='vet',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหตุ'),
        ),
        migrations.AddField(
            model_name='vet',
            name='role_level',
            field=models.CharField(blank=True, choices=[('แพทย์ฝึกหัด', 'แพทย์ฝึกหัด'), ('สัตวแพทย์', 'สัตวแพทย์'), ('สัตวแพทย์อาวุโส', 'สัตวแพทย์อาวุโส')], max_length=50, null=True, verbose_name='ระดับตำแหน่ง'),
        ),
        migrations.AddField(
            model_name='vet',
            name='university',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='มหาวิทยาลัย'),
        ),
        migrations.AddField(
            model_name='vet',
            name='working_hours',
            field=models.TextField(blank=True, null=True, verbose_name='ตารางปฏิบัติงาน'),
        ),
        migrations.AlterField(
            model_name='vet',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='เบอร์มือถือ'),
        ),
        migrations.AlterField(
            model_name='vet',
            name='specialization',
            field=models.CharField(blank=True, choices=[('อายุรกรรมทั่วไป', 'อายุรกรรมทั่วไป'), ('ศัลยกรรม', 'ศัลยกรรม'), ('สัตว์เลี้ยงพิเศษ (Exotic)', 'สัตว์เลี้ยงพิเศษ (Exotic)'), ('โรคผิวหนัง', 'โรคผิวหนัง'), ('หัวใจและหลอดเลือด', 'หัวใจและหลอดเลือด'), ('จักษุวิทยา', 'จักษุวิทยา')], max_length=100, null=True, verbose_name='สาขาความเชี่ยวชาญ'),
        ),
    ]
