# Generated by Django 5.2.11 on 2026-03-17 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_vet_name_vet_address_1_vet_address_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่นัด'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True, verbose_name='เวลานัด'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='ref_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='เลขที่ใบนัด'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service_type',
            field=models.CharField(blank=True, choices=[('ตรวจสุขภาพ', 'ตรวจสุขภาพ'), ('ฉีดวัคซีน', 'ฉีดวัคซีน'), ('ผ่าตัด', 'ผ่าตัด'), ('อาบน้ำ-ตัดขน', 'อาบน้ำ-ตัดขน'), ('ทำหมัน', 'ทำหมัน'), ('ทำฟัน', 'ทำฟัน'), ('อื่นๆ', 'อื่นๆ')], max_length=50, null=True, verbose_name='ประเภทบริการ'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('รอยืนยัน', 'รอยืนยัน'), ('ยืนยันแล้ว', 'ยืนยันแล้ว'), ('ยกเลิก', 'ยกเลิก'), ('เสร็จสิ้น', 'เสร็จสิ้น')], default='รอยืนยัน', max_length=20, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่-เวลา (เก่า)'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pet', verbose_name='สัตว์เลี้ยง'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='อาการ/หมายเหตุ'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='vet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vet', verbose_name='สัตวแพทย์'),
        ),
    ]
