# Generated by Django 5.2.11 on 2026-03-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Barcode'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ราคาทุน'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันหมดอายุ'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='generic_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ชื่อสามัญทางยา'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medicine_images/', verbose_name='รูปสินค้า'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='member_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ราคาสมาชิก'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='product_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='รหัสสินค้า'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='product_type',
            field=models.CharField(blank=True, choices=[('ยาเม็ด', 'ยาเม็ด'), ('ยาน้ำ', 'ยาน้ำ'), ('ยาฉีด', 'ยาฉีด'), ('วัคซีน', 'วัคซีน'), ('อุปกรณ์ทำแผล', 'อุปกรณ์ทำแผล'), ('อุปกรณ์การแพทย์', 'อุปกรณ์การแพทย์'), ('อาหารเสริม', 'อาหารเสริม'), ('อื่นๆ', 'อื่นๆ')], max_length=50, null=True, verbose_name='ประเภทสินค้า'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='reorder_point',
            field=models.IntegerField(default=10, verbose_name='จุดสั่งซื้อ (Reorder Point)'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ราคาขาย'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='supplier',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ผู้จำหน่าย/Supplier'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='unit',
            field=models.CharField(blank=True, choices=[('กล่อง', 'กล่อง'), ('แผง', 'แผง'), ('เม็ด', 'เม็ด'), ('ขวด', 'ขวด'), ('หลอด', 'หลอด'), ('ชิ้น', 'ชิ้น'), ('ซอง', 'ซอง'), ('ชุด', 'ชุด')], max_length=20, null=True, verbose_name='หน่วยนับ'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=7.0, max_digits=5, verbose_name='VAT (%)'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหตุ/วิธีเก็บรักษา'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=200, verbose_name='ชื่อยา/เวชภัณฑ์'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='จำนวนคงเหลือ'),
        ),
    ]
