# Generated by Django 5.2.11 on 2026-03-17 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_medicine_barcode_medicine_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='next_visit',
            field=models.DateField(blank=True, null=True, verbose_name='วันนัดครั้งต่อไป'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหตุเพิ่มเติม'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='ref_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='เลขที่เอกสาร'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='symptoms',
            field=models.TextField(blank=True, null=True, verbose_name='อาการที่พบ'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='อุณหภูมิ (°C)'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='visit_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่เข้ารับบริการ'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='visit_type',
            field=models.CharField(blank=True, choices=[('ตรวจสุขภาพทั่วไป', 'ตรวจสุขภาพทั่วไป'), ('ฉีดวัคซีน', 'ฉีดวัคซีน'), ('รักษาโรค', 'รักษาโรค'), ('ผ่าตัด', 'ผ่าตัด'), ('ทำหมัน', 'ทำหมัน'), ('อาบน้ำ-ตัดขน', 'อาบน้ำ-ตัดขน'), ('ฉุกเฉิน', 'ฉุกเฉิน'), ('อื่นๆ', 'อื่นๆ')], max_length=50, null=True, verbose_name='ประเภทการเข้ารับบริการ'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='น้ำหนัก (กก.)'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ค่าใช้จ่าย'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='diagnosis',
            field=models.TextField(verbose_name='ผลการวินิจฉัย'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='medicines',
            field=models.ManyToManyField(blank=True, to='myapp.medicine', verbose_name='ยาที่ใช้'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pet', verbose_name='สัตว์เลี้ยง'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='treatment',
            field=models.TextField(verbose_name='วิธีการรักษา'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='vet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.vet', verbose_name='สัตวแพทย์'),
        ),
    ]
