# Generated by Django 5.2.11 on 2026-03-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_medicalrecord_next_visit_medicalrecord_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='customer_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='รหัสลูกค้า'),
        ),
    ]
