# Generated by Django 5.2.11 on 2026-03-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_owner_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='สถานะการชำระเงิน'),
        ),
    ]
