# Generated by Django 5.2.11 on 2026-03-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_medicalrecord_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='full_description',
            field=models.TextField(blank=True, null=True, verbose_name='รายละเอียดสินค้าทั้งหมด'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='product_type',
            field=models.CharField(blank=True, choices=[('ยาเม็ด', 'ยาเม็ด'), ('ยาน้ำ', 'ยาน้ำ'), ('ยาฉีด', 'ยาฉีด'), ('วัคซีน', 'วัคซีน'), ('อุปกรณ์ทำแผล', 'อุปกรณ์ทำแผล'), ('อุปกรณ์การแพทย์', 'อุปกรณ์การแพทย์'), ('เวชภัณฑ์', 'เวชภัณฑ์'), ('อาหารเสริม', 'อาหารเสริม'), ('อื่นๆ', 'อื่นๆ')], max_length=50, null=True, verbose_name='ประเภทสินค้า'),
        ),
    ]
