# Generated by Django 5.2.11 on 2026-03-20 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_medicine_full_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='mobile',
        ),
    ]
