# Generated by Django 5.2.11 on 2026-03-31 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_appointment_date_time_remove_pet_mobile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่อตาราง')),
                ('record_id', models.IntegerField(blank=True, null=True, verbose_name='ID ของบรรทัดที่แก้')),
                ('action_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='ประเภทคำสั่ง')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='ค่าเดิม')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='ค่าใหม่')),
                ('changed_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='ผู้แก้')),
                ('change_date', models.DateTimeField(blank=True, null=True, verbose_name='ผู้แก้')),
            ],
            options={
                'db_table': 'myapp_audit_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VetLicenseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vet_id', models.IntegerField(blank=True, null=True, verbose_name='ID หมอ')),
                ('old_license_no', models.CharField(blank=True, max_length=50, null=True)),
                ('new_license_no', models.CharField(blank=True, max_length=50, null=True)),
                ('change_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'myapp_vet_license_log',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='owner',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_profile', to=settings.AUTH_USER_MODEL, verbose_name='บัญชีผู้ใช้'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'รอยืนยัน'), ('confirmed', 'ยืนยันแล้ว'), ('cancelled', 'ยกเลิก'), ('completed', 'เสร็จสิ้น')], default='pending', max_length=20, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
